// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// R_datey.cpp
integers cpp_asSafeIntegers(doubles x);
extern "C" SEXP _datey_cpp_asSafeIntegers(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_asSafeIntegers(cpp11::as_cpp<cpp11::decay_t<doubles>>(x)));
  END_CPP11
}
// R_datey.cpp
logicals cpp_dateyIsNA(integers clicks);
extern "C" SEXP _datey_cpp_dateyIsNA(SEXP clicks) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyIsNA(cpp11::as_cpp<cpp11::decay_t<integers>>(clicks)));
  END_CPP11
}
// R_datey.cpp
bool cpp_dateyAnyNA(integers clicks);
extern "C" SEXP _datey_cpp_dateyAnyNA(SEXP clicks) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyAnyNA(cpp11::as_cpp<cpp11::decay_t<integers>>(clicks)));
  END_CPP11
}
// R_datey.cpp
integers cpp_dateyFromYMDF(integers year, integers month, integers day, doubles dayFraction, bool strict);
extern "C" SEXP _datey_cpp_dateyFromYMDF(SEXP year, SEXP month, SEXP day, SEXP dayFraction, SEXP strict) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyFromYMDF(cpp11::as_cpp<cpp11::decay_t<integers>>(year), cpp11::as_cpp<cpp11::decay_t<integers>>(month), cpp11::as_cpp<cpp11::decay_t<integers>>(day), cpp11::as_cpp<cpp11::decay_t<doubles>>(dayFraction), cpp11::as_cpp<cpp11::decay_t<bool>>(strict)));
  END_CPP11
}
// R_datey.cpp
integers cpp_dateyFromYMDF_dblYMD(doubles year, doubles month, doubles day, doubles dayFraction, bool strict);
extern "C" SEXP _datey_cpp_dateyFromYMDF_dblYMD(SEXP year, SEXP month, SEXP day, SEXP dayFraction, SEXP strict) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyFromYMDF_dblYMD(cpp11::as_cpp<cpp11::decay_t<doubles>>(year), cpp11::as_cpp<cpp11::decay_t<doubles>>(month), cpp11::as_cpp<cpp11::decay_t<doubles>>(day), cpp11::as_cpp<cpp11::decay_t<doubles>>(dayFraction), cpp11::as_cpp<cpp11::decay_t<bool>>(strict)));
  END_CPP11
}
// R_datey.cpp
list cpp_dateyToYMDF(integers clicks);
extern "C" SEXP _datey_cpp_dateyToYMDF(SEXP clicks) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyToYMDF(cpp11::as_cpp<cpp11::decay_t<integers>>(clicks)));
  END_CPP11
}
// R_datey.cpp
integers cpp_dateyToY(integers clicks);
extern "C" SEXP _datey_cpp_dateyToY(SEXP clicks) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyToY(cpp11::as_cpp<cpp11::decay_t<integers>>(clicks)));
  END_CPP11
}
// R_datey.cpp
integers cpp_dateyToM(integers clicks);
extern "C" SEXP _datey_cpp_dateyToM(SEXP clicks) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyToM(cpp11::as_cpp<cpp11::decay_t<integers>>(clicks)));
  END_CPP11
}
// R_datey.cpp
integers cpp_dateyToD(integers clicks);
extern "C" SEXP _datey_cpp_dateyToD(SEXP clicks) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyToD(cpp11::as_cpp<cpp11::decay_t<integers>>(clicks)));
  END_CPP11
}
// R_datey.cpp
doubles cpp_dateyToF(integers clicks);
extern "C" SEXP _datey_cpp_dateyToF(SEXP clicks) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyToF(cpp11::as_cpp<cpp11::decay_t<integers>>(clicks)));
  END_CPP11
}
// R_datey.cpp
integers cpp_dateyWithNewDayFraction(integers clicks, doubles dayFraction, bool strict);
extern "C" SEXP _datey_cpp_dateyWithNewDayFraction(SEXP clicks, SEXP dayFraction, SEXP strict) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyWithNewDayFraction(cpp11::as_cpp<cpp11::decay_t<integers>>(clicks), cpp11::as_cpp<cpp11::decay_t<doubles>>(dayFraction), cpp11::as_cpp<cpp11::decay_t<bool>>(strict)));
  END_CPP11
}
// R_datey.cpp
integers cpp_dateyFromRDate(doubles rDate, bool strict);
extern "C" SEXP _datey_cpp_dateyFromRDate(SEXP rDate, SEXP strict) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyFromRDate(cpp11::as_cpp<cpp11::decay_t<doubles>>(rDate), cpp11::as_cpp<cpp11::decay_t<bool>>(strict)));
  END_CPP11
}
// R_datey.cpp
integers cpp_dateyFromRDateAndFraction(doubles rDate, doubles dayFraction, bool strict);
extern "C" SEXP _datey_cpp_dateyFromRDateAndFraction(SEXP rDate, SEXP dayFraction, SEXP strict) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyFromRDateAndFraction(cpp11::as_cpp<cpp11::decay_t<doubles>>(rDate), cpp11::as_cpp<cpp11::decay_t<doubles>>(dayFraction), cpp11::as_cpp<cpp11::decay_t<bool>>(strict)));
  END_CPP11
}
// R_datey.cpp
strings cpp_dateyToRString(integers clicks, bool includeDayFraction);
extern "C" SEXP _datey_cpp_dateyToRString(SEXP clicks, SEXP includeDayFraction) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyToRString(cpp11::as_cpp<cpp11::decay_t<integers>>(clicks), cpp11::as_cpp<cpp11::decay_t<bool>>(includeDayFraction)));
  END_CPP11
}
// R_datey.cpp
integers cpp_dateyFromRStringOnly(strings x, bool strict, bool blankIsNA);
extern "C" SEXP _datey_cpp_dateyFromRStringOnly(SEXP x, SEXP strict, SEXP blankIsNA) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyFromRStringOnly(cpp11::as_cpp<cpp11::decay_t<strings>>(x), cpp11::as_cpp<cpp11::decay_t<bool>>(strict), cpp11::as_cpp<cpp11::decay_t<bool>>(blankIsNA)));
  END_CPP11
}
// R_datey.cpp
integers cpp_dateyFromRStringAndDayFraction(strings x, doubles dayFraction, bool strict, bool blankIsNA);
extern "C" SEXP _datey_cpp_dateyFromRStringAndDayFraction(SEXP x, SEXP dayFraction, SEXP strict, SEXP blankIsNA) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyFromRStringAndDayFraction(cpp11::as_cpp<cpp11::decay_t<strings>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(dayFraction), cpp11::as_cpp<cpp11::decay_t<bool>>(strict), cpp11::as_cpp<cpp11::decay_t<bool>>(blankIsNA)));
  END_CPP11
}
// R_datey_interval.cpp
doubles cpp_dateyInterval(integers start, integers end, bool strict);
extern "C" SEXP _datey_cpp_dateyInterval(SEXP start, SEXP end, SEXP strict) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyInterval(cpp11::as_cpp<cpp11::decay_t<integers>>(start), cpp11::as_cpp<cpp11::decay_t<integers>>(end), cpp11::as_cpp<cpp11::decay_t<bool>>(strict)));
  END_CPP11
}
// R_datey_interval.cpp
integers cpp_dateyIntervalStart(doubles interval);
extern "C" SEXP _datey_cpp_dateyIntervalStart(SEXP interval) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyIntervalStart(cpp11::as_cpp<cpp11::decay_t<doubles>>(interval)));
  END_CPP11
}
// R_datey_interval.cpp
integers cpp_dateyIntervalEnd(doubles interval);
extern "C" SEXP _datey_cpp_dateyIntervalEnd(SEXP interval) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyIntervalEnd(cpp11::as_cpp<cpp11::decay_t<doubles>>(interval)));
  END_CPP11
}
// R_datey_interval.cpp
integers cpp_dateyIntervalDuration(doubles interval);
extern "C" SEXP _datey_cpp_dateyIntervalDuration(SEXP interval) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyIntervalDuration(cpp11::as_cpp<cpp11::decay_t<doubles>>(interval)));
  END_CPP11
}
// R_datey_interval.cpp
logicals cpp_dateyIntervalIsNA(doubles interval);
extern "C" SEXP _datey_cpp_dateyIntervalIsNA(SEXP interval) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyIntervalIsNA(cpp11::as_cpp<cpp11::decay_t<doubles>>(interval)));
  END_CPP11
}
// R_datey_interval.cpp
bool cpp_dateyIntervalAnyNA(doubles interval);
extern "C" SEXP _datey_cpp_dateyIntervalAnyNA(SEXP interval) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyIntervalAnyNA(cpp11::as_cpp<cpp11::decay_t<doubles>>(interval)));
  END_CPP11
}
// R_datey_interval.cpp
logicals cpp_dateyIntervalIsProper(doubles interval);
extern "C" SEXP _datey_cpp_dateyIntervalIsProper(SEXP interval) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyIntervalIsProper(cpp11::as_cpp<cpp11::decay_t<doubles>>(interval)));
  END_CPP11
}
// R_datey_interval.cpp
bool cpp_dateyIntervalAllProper(doubles interval);
extern "C" SEXP _datey_cpp_dateyIntervalAllProper(SEXP interval) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyIntervalAllProper(cpp11::as_cpp<cpp11::decay_t<doubles>>(interval)));
  END_CPP11
}
// R_datey_interval.cpp
logicals cpp_dateyIntervalIsCollapsed(doubles interval);
extern "C" SEXP _datey_cpp_dateyIntervalIsCollapsed(SEXP interval) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyIntervalIsCollapsed(cpp11::as_cpp<cpp11::decay_t<doubles>>(interval)));
  END_CPP11
}
// R_datey_interval.cpp
bool cpp_dateyIntervalAllCollapsed(doubles interval);
extern "C" SEXP _datey_cpp_dateyIntervalAllCollapsed(SEXP interval) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyIntervalAllCollapsed(cpp11::as_cpp<cpp11::decay_t<doubles>>(interval)));
  END_CPP11
}
// R_datey_interval.cpp
bool cpp_dateyIntervalAnyCollapsed(doubles interval);
extern "C" SEXP _datey_cpp_dateyIntervalAnyCollapsed(SEXP interval) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyIntervalAnyCollapsed(cpp11::as_cpp<cpp11::decay_t<doubles>>(interval)));
  END_CPP11
}
// R_datey_interval.cpp
logicals cpp_dateyIntervalIncludes(doubles interval, integers value);
extern "C" SEXP _datey_cpp_dateyIntervalIncludes(SEXP interval, SEXP value) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyIntervalIncludes(cpp11::as_cpp<cpp11::decay_t<doubles>>(interval), cpp11::as_cpp<cpp11::decay_t<integers>>(value)));
  END_CPP11
}
// R_datey_interval.cpp
strings cpp_dateyIntervalToRString(doubles interval, bool includeDayFraction);
extern "C" SEXP _datey_cpp_dateyIntervalToRString(SEXP interval, SEXP includeDayFraction) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_dateyIntervalToRString(cpp11::as_cpp<cpp11::decay_t<doubles>>(interval), cpp11::as_cpp<cpp11::decay_t<bool>>(includeDayFraction)));
  END_CPP11
}
// R_durationy.cpp
logicals cpp_durationyIsNA(integers clicks);
extern "C" SEXP _datey_cpp_durationyIsNA(SEXP clicks) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_durationyIsNA(cpp11::as_cpp<cpp11::decay_t<integers>>(clicks)));
  END_CPP11
}
// R_durationy.cpp
bool cpp_durationyAnyNA(integers clicks);
extern "C" SEXP _datey_cpp_durationyAnyNA(SEXP clicks) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_durationyAnyNA(cpp11::as_cpp<cpp11::decay_t<integers>>(clicks)));
  END_CPP11
}
// R_durationy.cpp
strings cpp_durationyToRString(integers clicks, bool includePlusSign, bool useTrueMinusSign, strings yearUnit);
extern "C" SEXP _datey_cpp_durationyToRString(SEXP clicks, SEXP includePlusSign, SEXP useTrueMinusSign, SEXP yearUnit) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_durationyToRString(cpp11::as_cpp<cpp11::decay_t<integers>>(clicks), cpp11::as_cpp<cpp11::decay_t<bool>>(includePlusSign), cpp11::as_cpp<cpp11::decay_t<bool>>(useTrueMinusSign), cpp11::as_cpp<cpp11::decay_t<strings>>(yearUnit)));
  END_CPP11
}
// R_durationy.cpp
integers cpp_durationyFromRString(strings x, bool strict, bool blankIsNA, strings yearUnit);
extern "C" SEXP _datey_cpp_durationyFromRString(SEXP x, SEXP strict, SEXP blankIsNA, SEXP yearUnit) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_durationyFromRString(cpp11::as_cpp<cpp11::decay_t<strings>>(x), cpp11::as_cpp<cpp11::decay_t<bool>>(strict), cpp11::as_cpp<cpp11::decay_t<bool>>(blankIsNA), cpp11::as_cpp<cpp11::decay_t<strings>>(yearUnit)));
  END_CPP11
}
// R_is_leap_year.cpp
logicals cpp_isLeapYear_integer(const integers& year);
extern "C" SEXP _datey_cpp_isLeapYear_integer(SEXP year) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_isLeapYear_integer(cpp11::as_cpp<cpp11::decay_t<const integers&>>(year)));
  END_CPP11
}
// R_is_leap_year.cpp
logicals cpp_isLeapYear_double(const doubles& year);
extern "C" SEXP _datey_cpp_isLeapYear_double(SEXP year) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_isLeapYear_double(cpp11::as_cpp<cpp11::decay_t<const doubles&>>(year)));
  END_CPP11
}
// R_is_leap_year.cpp
logicals cpp_isLeapYear_datey(const integers& datey);
extern "C" SEXP _datey_cpp_isLeapYear_datey(SEXP datey) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_isLeapYear_datey(cpp11::as_cpp<cpp11::decay_t<const integers&>>(datey)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_datey_cpp_asSafeIntegers",                 (DL_FUNC) &_datey_cpp_asSafeIntegers,                 1},
    {"_datey_cpp_dateyAnyNA",                     (DL_FUNC) &_datey_cpp_dateyAnyNA,                     1},
    {"_datey_cpp_dateyFromRDate",                 (DL_FUNC) &_datey_cpp_dateyFromRDate,                 2},
    {"_datey_cpp_dateyFromRDateAndFraction",      (DL_FUNC) &_datey_cpp_dateyFromRDateAndFraction,      3},
    {"_datey_cpp_dateyFromRStringAndDayFraction", (DL_FUNC) &_datey_cpp_dateyFromRStringAndDayFraction, 4},
    {"_datey_cpp_dateyFromRStringOnly",           (DL_FUNC) &_datey_cpp_dateyFromRStringOnly,           3},
    {"_datey_cpp_dateyFromYMDF",                  (DL_FUNC) &_datey_cpp_dateyFromYMDF,                  5},
    {"_datey_cpp_dateyFromYMDF_dblYMD",           (DL_FUNC) &_datey_cpp_dateyFromYMDF_dblYMD,           5},
    {"_datey_cpp_dateyInterval",                  (DL_FUNC) &_datey_cpp_dateyInterval,                  3},
    {"_datey_cpp_dateyIntervalAllCollapsed",      (DL_FUNC) &_datey_cpp_dateyIntervalAllCollapsed,      1},
    {"_datey_cpp_dateyIntervalAllProper",         (DL_FUNC) &_datey_cpp_dateyIntervalAllProper,         1},
    {"_datey_cpp_dateyIntervalAnyCollapsed",      (DL_FUNC) &_datey_cpp_dateyIntervalAnyCollapsed,      1},
    {"_datey_cpp_dateyIntervalAnyNA",             (DL_FUNC) &_datey_cpp_dateyIntervalAnyNA,             1},
    {"_datey_cpp_dateyIntervalDuration",          (DL_FUNC) &_datey_cpp_dateyIntervalDuration,          1},
    {"_datey_cpp_dateyIntervalEnd",               (DL_FUNC) &_datey_cpp_dateyIntervalEnd,               1},
    {"_datey_cpp_dateyIntervalIncludes",          (DL_FUNC) &_datey_cpp_dateyIntervalIncludes,          2},
    {"_datey_cpp_dateyIntervalIsCollapsed",       (DL_FUNC) &_datey_cpp_dateyIntervalIsCollapsed,       1},
    {"_datey_cpp_dateyIntervalIsNA",              (DL_FUNC) &_datey_cpp_dateyIntervalIsNA,              1},
    {"_datey_cpp_dateyIntervalIsProper",          (DL_FUNC) &_datey_cpp_dateyIntervalIsProper,          1},
    {"_datey_cpp_dateyIntervalStart",             (DL_FUNC) &_datey_cpp_dateyIntervalStart,             1},
    {"_datey_cpp_dateyIntervalToRString",         (DL_FUNC) &_datey_cpp_dateyIntervalToRString,         2},
    {"_datey_cpp_dateyIsNA",                      (DL_FUNC) &_datey_cpp_dateyIsNA,                      1},
    {"_datey_cpp_dateyToD",                       (DL_FUNC) &_datey_cpp_dateyToD,                       1},
    {"_datey_cpp_dateyToF",                       (DL_FUNC) &_datey_cpp_dateyToF,                       1},
    {"_datey_cpp_dateyToM",                       (DL_FUNC) &_datey_cpp_dateyToM,                       1},
    {"_datey_cpp_dateyToRString",                 (DL_FUNC) &_datey_cpp_dateyToRString,                 2},
    {"_datey_cpp_dateyToY",                       (DL_FUNC) &_datey_cpp_dateyToY,                       1},
    {"_datey_cpp_dateyToYMDF",                    (DL_FUNC) &_datey_cpp_dateyToYMDF,                    1},
    {"_datey_cpp_dateyWithNewDayFraction",        (DL_FUNC) &_datey_cpp_dateyWithNewDayFraction,        3},
    {"_datey_cpp_durationyAnyNA",                 (DL_FUNC) &_datey_cpp_durationyAnyNA,                 1},
    {"_datey_cpp_durationyFromRString",           (DL_FUNC) &_datey_cpp_durationyFromRString,           4},
    {"_datey_cpp_durationyIsNA",                  (DL_FUNC) &_datey_cpp_durationyIsNA,                  1},
    {"_datey_cpp_durationyToRString",             (DL_FUNC) &_datey_cpp_durationyToRString,             4},
    {"_datey_cpp_isLeapYear_datey",               (DL_FUNC) &_datey_cpp_isLeapYear_datey,               1},
    {"_datey_cpp_isLeapYear_double",              (DL_FUNC) &_datey_cpp_isLeapYear_double,              1},
    {"_datey_cpp_isLeapYear_integer",             (DL_FUNC) &_datey_cpp_isLeapYear_integer,             1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_datey(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
