// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// R_datey.cpp
integers cpp_safeDoubleToInteger(doubles x);
extern "C" SEXP _datey_cpp_safeDoubleToInteger(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_safeDoubleToInteger(cpp11::as_cpp<cpp11::decay_t<doubles>>(x)));
  END_CPP11
}
// R_datey.cpp
integers cpp_clicksFromYMDF(integers year, integers month, integers day, doubles dayFraction);
extern "C" SEXP _datey_cpp_clicksFromYMDF(SEXP year, SEXP month, SEXP day, SEXP dayFraction) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_clicksFromYMDF(cpp11::as_cpp<cpp11::decay_t<integers>>(year), cpp11::as_cpp<cpp11::decay_t<integers>>(month), cpp11::as_cpp<cpp11::decay_t<integers>>(day), cpp11::as_cpp<cpp11::decay_t<doubles>>(dayFraction)));
  END_CPP11
}
// R_datey.cpp
list cpp_clicksToYMDF(integers clicks);
extern "C" SEXP _datey_cpp_clicksToYMDF(SEXP clicks) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_clicksToYMDF(cpp11::as_cpp<cpp11::decay_t<integers>>(clicks)));
  END_CPP11
}
// R_datey.cpp
logicals cpp_isLeapYear(integers year);
extern "C" SEXP _datey_cpp_isLeapYear(SEXP year) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_isLeapYear(cpp11::as_cpp<cpp11::decay_t<integers>>(year)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_datey_cpp_clicksFromYMDF",      (DL_FUNC) &_datey_cpp_clicksFromYMDF,      4},
    {"_datey_cpp_clicksToYMDF",        (DL_FUNC) &_datey_cpp_clicksToYMDF,        1},
    {"_datey_cpp_isLeapYear",          (DL_FUNC) &_datey_cpp_isLeapYear,          1},
    {"_datey_cpp_safeDoubleToInteger", (DL_FUNC) &_datey_cpp_safeDoubleToInteger, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_datey(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
