# Generated by cpp11: do not edit by hand

cpp_isLeapYear <- function(year) {
  .Call(`_datey_cpp_isLeapYear`, year)
}

cpp_IntegralDoubleToInteger <- function(x) {
  .Call(`_datey_cpp_IntegralDoubleToInteger`, x)
}

cpp_dateyFromYMDF <- function(year, month, day, dayFraction) {
  .Call(`_datey_cpp_dateyFromYMDF`, year, month, day, dayFraction)
}

cpp_dateyToYMDF <- function(datey) {
  .Call(`_datey_cpp_dateyToYMDF`, datey)
}

cpp_dateyFromRDate <- function(rDate, dayFraction) {
  .Call(`_datey_cpp_dateyFromRDate`, rDate, dayFraction)
}

cpp_dateyToRString <- function(datey) {
  .Call(`_datey_cpp_dateyToRString`, datey)
}

cpp_dateyFromRStringOnly <- function(s) {
  .Call(`_datey_cpp_dateyFromRStringOnly`, s)
}

cpp_dateyFromRStringAndDayFraction <- function(s, dayFraction) {
  .Call(`_datey_cpp_dateyFromRStringAndDayFraction`, s, dayFraction)
}
