# Generated by cpp11: do not edit by hand

cpp_asSafeIntegers <- function(x) {
  .Call(`_datey_cpp_asSafeIntegers`, x)
}

cpp_dateyIsNA <- function(clicks) {
  .Call(`_datey_cpp_dateyIsNA`, clicks)
}

cpp_dateyAnyNA <- function(clicks) {
  .Call(`_datey_cpp_dateyAnyNA`, clicks)
}

cpp_dateyFromYMDF <- function(year, month, day, dayFraction, strict) {
  .Call(`_datey_cpp_dateyFromYMDF`, year, month, day, dayFraction, strict)
}

cpp_dateyFromYMDF_dblYMD <- function(year, month, day, dayFraction, strict) {
  .Call(`_datey_cpp_dateyFromYMDF_dblYMD`, year, month, day, dayFraction, strict)
}

cpp_dateyToYMDF <- function(clicks) {
  .Call(`_datey_cpp_dateyToYMDF`, clicks)
}

cpp_dateyToY <- function(clicks) {
  .Call(`_datey_cpp_dateyToY`, clicks)
}

cpp_dateyToM <- function(clicks) {
  .Call(`_datey_cpp_dateyToM`, clicks)
}

cpp_dateyToD <- function(clicks) {
  .Call(`_datey_cpp_dateyToD`, clicks)
}

cpp_dateyToF <- function(clicks) {
  .Call(`_datey_cpp_dateyToF`, clicks)
}

cpp_dateyWithNewDayFraction <- function(clicks, dayFraction, strict) {
  .Call(`_datey_cpp_dateyWithNewDayFraction`, clicks, dayFraction, strict)
}

cpp_dateyFromRDate <- function(rDate, strict) {
  .Call(`_datey_cpp_dateyFromRDate`, rDate, strict)
}

cpp_dateyFromRDateAndFraction <- function(rDate, dayFraction, strict) {
  .Call(`_datey_cpp_dateyFromRDateAndFraction`, rDate, dayFraction, strict)
}

cpp_dateyToRString <- function(clicks, includeDayFraction) {
  .Call(`_datey_cpp_dateyToRString`, clicks, includeDayFraction)
}

cpp_dateyFromRStringOnly <- function(x, strict, blankIsNA) {
  .Call(`_datey_cpp_dateyFromRStringOnly`, x, strict, blankIsNA)
}

cpp_dateyFromRStringAndDayFraction <- function(x, dayFraction, strict, blankIsNA) {
  .Call(`_datey_cpp_dateyFromRStringAndDayFraction`, x, dayFraction, strict, blankIsNA)
}

cpp_dateyInterval <- function(start, end, strict) {
  .Call(`_datey_cpp_dateyInterval`, start, end, strict)
}

cpp_dateyIntervalStart <- function(interval) {
  .Call(`_datey_cpp_dateyIntervalStart`, interval)
}

cpp_dateyIntervalEnd <- function(interval) {
  .Call(`_datey_cpp_dateyIntervalEnd`, interval)
}

cpp_dateyIntervalDuration <- function(interval) {
  .Call(`_datey_cpp_dateyIntervalDuration`, interval)
}

cpp_dateyIntervalIsNA <- function(interval) {
  .Call(`_datey_cpp_dateyIntervalIsNA`, interval)
}

cpp_dateyIntervalAnyNA <- function(interval) {
  .Call(`_datey_cpp_dateyIntervalAnyNA`, interval)
}

cpp_dateyIntervalIsProper <- function(interval) {
  .Call(`_datey_cpp_dateyIntervalIsProper`, interval)
}

cpp_dateyIntervalAllProper <- function(interval) {
  .Call(`_datey_cpp_dateyIntervalAllProper`, interval)
}

cpp_dateyIntervalIsCollapsed <- function(interval) {
  .Call(`_datey_cpp_dateyIntervalIsCollapsed`, interval)
}

cpp_dateyIntervalAllCollapsed <- function(interval) {
  .Call(`_datey_cpp_dateyIntervalAllCollapsed`, interval)
}

cpp_dateyIntervalAnyCollapsed <- function(interval) {
  .Call(`_datey_cpp_dateyIntervalAnyCollapsed`, interval)
}

cpp_dateyIntervalIncludes <- function(interval, value) {
  .Call(`_datey_cpp_dateyIntervalIncludes`, interval, value)
}

cpp_dateyIntervalToRString <- function(interval, includeDayFraction) {
  .Call(`_datey_cpp_dateyIntervalToRString`, interval, includeDayFraction)
}

cpp_durationyIsNA <- function(clicks) {
  .Call(`_datey_cpp_durationyIsNA`, clicks)
}

cpp_durationyAnyNA <- function(clicks) {
  .Call(`_datey_cpp_durationyAnyNA`, clicks)
}

cpp_durationyToRString <- function(clicks, includePlusSign, useTrueMinusSign, yearUnit) {
  .Call(`_datey_cpp_durationyToRString`, clicks, includePlusSign, useTrueMinusSign, yearUnit)
}

cpp_durationyFromRString <- function(x, strict, blankIsNA, yearUnit) {
  .Call(`_datey_cpp_durationyFromRString`, x, strict, blankIsNA, yearUnit)
}

cpp_isLeapYear_integer <- function(year) {
  .Call(`_datey_cpp_isLeapYear_integer`, year)
}

cpp_isLeapYear_double <- function(year) {
  .Call(`_datey_cpp_isLeapYear_double`, year)
}

cpp_isLeapYear_datey <- function(datey) {
  .Call(`_datey_cpp_isLeapYear_datey`, datey)
}
