# Generated by cpp11: do not edit by hand

cpp_dateyFromYMDF <- function(year, month, day, dayFraction) {
  .Call(`_datey_cpp_dateyFromYMDF`, year, month, day, dayFraction)
}

cpp_dateyToYMDF <- function(datey) {
  .Call(`_datey_cpp_dateyToYMDF`, datey)
}

cpp_dateyWithNewDayFraction <- function(datey, dayFraction) {
  .Call(`_datey_cpp_dateyWithNewDayFraction`, datey, dayFraction)
}

cpp_dateyFromRDate <- function(rDate) {
  .Call(`_datey_cpp_dateyFromRDate`, rDate)
}

cpp_dateyFromRDateAndFraction <- function(rDate, dayFraction) {
  .Call(`_datey_cpp_dateyFromRDateAndFraction`, rDate, dayFraction)
}

cpp_dateyToRString <- function(datey, includeDayFraction) {
  .Call(`_datey_cpp_dateyToRString`, datey, includeDayFraction)
}

cpp_dateyFromRStringOnly <- function(s) {
  .Call(`_datey_cpp_dateyFromRStringOnly`, s)
}

cpp_dateyFromRStringAndDayFraction <- function(s, dayFraction) {
  .Call(`_datey_cpp_dateyFromRStringAndDayFraction`, s, dayFraction)
}

cpp_isLeapYear_integer <- function(year) {
  .Call(`_datey_cpp_isLeapYear_integer`, year)
}

cpp_isLeapYear_double <- function(year) {
  .Call(`_datey_cpp_isLeapYear_double`, year)
}

cpp_isLeapYear_datey <- function(datey) {
  .Call(`_datey_cpp_isLeapYear_datey`, datey)
}
